export const types={
    GET_NEEDY_REQ_START:'GET_NEEDY_REQ_START',
    GET_NEEDY_REQ_FAILED:'GET_NEEDY_REQ_FAILED',
    GET_NEEDY_REQ_SUCCESS:'GET_NEEDY_REQ_SUCCESS',

    APPROVE_NEEDY_START:'APPROVE_NEEDY_START',
    APPROVE_NEEDY_FAILED:'APPROVE_NEEDY_FAILED',
    APPROVE_NEEDY_SUCCESS:'APPROVE_NEEDY_SUCCESS',

    REJECT_NEEDY_START:'REJECT_NEEDY_START',
    REJECT_NEEDY_FAILED:'REJECT_NEEDY_FAILED',
    REJECT_NEEDY_SUCCESS:'REJECT_NEEDY_SUCCESS',

    GET_DONOR_REQ_START:'GET_DONOR_REQ_START',
    GET_DONOR_REQ_FAILED:'GET_DONOR_REQ_FAILED',
    GET_DONOR_REQ_SUCCESS:'GET_DONOR_REQ_SUCCESS',

    APPROVE_DONOR_START:'APPROVE_DONOR_START',
    APPROVE_DONOR_FAILED:'APPROVE_DONOR_FAILED',
    APPROVE_DONOR_SUCCESS:'APPROVE_DONOR_SUCCESS',

    REJECT_DONOR_START:'REJECT_DONOR_START',
    REJECT_DONOR_FAILED:'REJECT_DONOR_FAILED',
    REJECT_DONOR_SUCCESS:'REJECT_DONOR_SUCCESS',
}