import Head from 'next/head'
import Image from 'next/image'
import { Header, Menu } from '../components'
import { Provider } from 'react-redux'
import { Store } from '../store/Store'

export default function Home() {
  return (
    <Provider store={Store}>
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Header/>
        <Menu/>
      </main>

      <footer>
        
      </footer>
    </div>
    </Provider>
  )
}
